[package]
name = "gifc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
gif = "0.11"
atty = "0.2"
gifski = "1.4"
fontdue = "0.5"
imgref = "1.9"
rgb = "0.8"